export type PaintSwatch = { name: string; hex: string };

/** Palette estesa: clic per applicare il HEX al configuratore 3D. */
export const CAR_PAINT_PRESETS: PaintSwatch[] = [
  { name: "Rosso Corsa", hex: "#d32f2f" },
  { name: "Rosso fuoco", hex: "#b71c1c" },
  { name: "Rosso bordeaux", hex: "#880e4f" },
  { name: "Arancio racing", hex: "#e65100" },
  { name: "Giallo racing", hex: "#f9a825" },
  { name: "Oro metallizzato", hex: "#c6a052" },
  { name: "Verde British", hex: "#1b5e20" },
  { name: "Verde racing", hex: "#2e7d32" },
  { name: "Verde menta", hex: "#00b894" },
  { name: "Blu Royal", hex: "#1565c0" },
  { name: "Blu notte", hex: "#0d47a1" },
  { name: "Blu elettrico", hex: "#2962ff" },
  { name: "Blu petrolio", hex: "#004d6b" },
  { name: "Azzurro ghiaccio", hex: "#4fc3f7" },
  { name: "Viola prugna", hex: "#4a148c" },
  { name: "Viola perla", hex: "#6a1b9a" },
  { name: "Nero profondo", hex: "#212121" },
  { name: "Grigio antracite", hex: "#37474f" },
  { name: "Grigio piombo", hex: "#546e7a" },
  { name: "Argento", hex: "#90a4ae" },
  { name: "Grigio chiaro", hex: "#cfd8dc" },
  { name: "Bianco ghiaccio", hex: "#eceff1" },
  { name: "Bianco perla", hex: "#fafafa" },
  { name: "Beige sabbia", hex: "#d7ccc8" },
  { name: "Marrone terra", hex: "#5d4037" },
  { name: "Bronzo", hex: "#8d6e63" },
  { name: "Champagne", hex: "#d4c4a8" },
  { name: "Rame metallizzato", hex: "#b87333" },
  { name: "Rosa quarzo", hex: "#f48fb1" },
  { name: "Turchese", hex: "#00897b" },
  { name: "Lime acido", hex: "#c0ca33" },
  { name: "Blu Alpine", hex: "#0277bd" },
  { name: "Grigio Nardo", hex: "#6d6d6d" },
  { name: "Verde militare", hex: "#33691e" },
  { name: "Blu Misano", hex: "#01579b" },
  { name: "Bianco pastello", hex: "#f5f5f5" },
];
